sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-23.0.3
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - sh script.sh

notifications:
  email: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
