sudo: true

language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - android-24
    - build-tools-24.0.2
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_install:
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - pip install --user codecov

script:
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - sh script.sh

after_success:
  - .buildscript/deploy_snapshot.sh

notifications:
  email: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - codecov
